### PR TITLE
Impl tar check (TODO: add multiple arch gnu tar component.)

### PR DESCRIPTION
**Pull request by xiaoyangnoob**
https://github.com/Magisk-Modules-Alt-Repo/chroot-distro/issues/35

### CODE REVIEW

**Comment by xiaoyangnoob** [comment]
Hmm... rootfs tarball is GNU format and it can't unpack with busybox tar.

**Comment by xiaoyangnoob** [comment]
Draft

**Comment by xiaoyangnoob** [comment]
I am working on bug fix. Just a moment.

**Comment by xiaoyangnoob** [comment]
I am sorry i can't create a magisk module... Let's take this discussion to the issue tracker for further conversation.

**Comment by xiaoyangnoob** [comment]
Close it now

**Comment by jjkola** [comment]
We can't expect full tar, nor do we want to include Busybox and/or tar. I have a PR that will fix this issue without extra dependencies.

**Pull request closed without merging**
